name: number_translator
description: "Number Translator is a Dart package for converting numbers between different languages with ease."
version: 1.0.0
homepage: https://github.com/thetahmeed/number_translator

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
